// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6qTJjo4Yl8MCC4qVFz73Wd7KQQUu4fK8',
    appId: '1:76104442308:web:c2f1ae7a31d9a9806a4491',
    messagingSenderId: '76104442308',
    projectId: 'finance-app-c18cb',
    authDomain: 'finance-app-c18cb.firebaseapp.com',
    storageBucket: 'finance-app-c18cb.firebasestorage.app',
    measurementId: 'G-8GE62NZ1H5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe358FY-IVdM7KL-DuSmIGQnQdMVLO4IE',
    appId: '1:76104442308:android:776c3d89e8950c476a4491',
    messagingSenderId: '76104442308',
    projectId: 'finance-app-c18cb',
    storageBucket: 'finance-app-c18cb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMJG6WNCug3ZLdWd309GUYPJh61HgnRGQ',
    appId: '1:76104442308:ios:c1ee286f91e0ced66a4491',
    messagingSenderId: '76104442308',
    projectId: 'finance-app-c18cb',
    storageBucket: 'finance-app-c18cb.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMJG6WNCug3ZLdWd309GUYPJh61HgnRGQ',
    appId: '1:76104442308:ios:c1ee286f91e0ced66a4491',
    messagingSenderId: '76104442308',
    projectId: 'finance-app-c18cb',
    storageBucket: 'finance-app-c18cb.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6qTJjo4Yl8MCC4qVFz73Wd7KQQUu4fK8',
    appId: '1:76104442308:web:6b9c58dc55da98c66a4491',
    messagingSenderId: '76104442308',
    projectId: 'finance-app-c18cb',
    authDomain: 'finance-app-c18cb.firebaseapp.com',
    storageBucket: 'finance-app-c18cb.firebasestorage.app',
    measurementId: 'G-36MEL5Z4RE',
  );

}